"use strict";(self.webpackChunkrust_book_abridged=self.webpackChunkrust_book_abridged||[]).push([[617],{3905:(e,t,n)=>{n.d(t,{Zo:()=>u,kt:()=>c});var r=n(7294);function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,r,a=function(e,t){if(null==e)return{};var n,r,a={},o=Object.keys(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var s=r.createContext({}),p=function(e){var t=r.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},u=function(e){var t=p(e.components);return r.createElement(s.Provider,{value:t},e.children)},h="mdxType",d={inlineCode:"code",wrapper:function(e){var t=e.children;return r.createElement(r.Fragment,{},t)}},m=r.forwardRef((function(e,t){var n=e.components,a=e.mdxType,o=e.originalType,s=e.parentName,u=l(e,["components","mdxType","originalType","parentName"]),h=p(n),m=a,c=h["".concat(s,".").concat(m)]||h[m]||d[m]||o;return n?r.createElement(c,i(i({ref:t},u),{},{components:n})):r.createElement(c,i({ref:t},u))}));function c(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var o=n.length,i=new Array(o);i[0]=m;var l={};for(var s in t)hasOwnProperty.call(t,s)&&(l[s]=t[s]);l.originalType=e,l[h]="string"==typeof e?e:a,i[1]=l;for(var p=2;p<o;p++)i[p]=n[p];return r.createElement.apply(null,i)}return r.createElement.apply(null,n)}m.displayName="MDXCreateElement"},1480:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>s,contentTitle:()=>i,default:()=>d,frontMatter:()=>o,metadata:()=>l,toc:()=>p});var r=n(7462),a=(n(7294),n(3905));const o={},i="9 - Error Handling",l={unversionedId:"ch09-error-handling",id:"ch09-error-handling",title:"9 - Error Handling",description:"Rust has a tiered error-handling scheme:",source:"@site/docs/ch09-error-handling.md",sourceDirName:".",slug:"/ch09-error-handling",permalink:"/rust-book-abridged/ch09-error-handling",draft:!1,editUrl:"https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/docs/ch09-error-handling.md",tags:[],version:"current",frontMatter:{},sidebar:"tutorialSidebar",previous:{title:"8 - Common Collections",permalink:"/rust-book-abridged/ch08-common-collections"},next:{title:"10 - Generic Types, Traits, and Lifetimes",permalink:"/rust-book-abridged/category/10---generic-types-traits-and-lifetimes"}},s={},p=[{value:"9.1 - Unrecoverable Errors with <code>panic!</code>",id:"91---unrecoverable-errors-with-panic",level:2},{value:"Unwinding the Stack or Aborting in Response to a Panic",id:"unwinding-the-stack-or-aborting-in-response-to-a-panic",level:3},{value:"9.2 - Recoverable Errors with Result",id:"92---recoverable-errors-with-result",level:2},{value:"Matching on Different Errors",id:"matching-on-different-errors",level:3},{value:"Alternatives to Using match with <code>Result&lt;T, E&gt;</code>",id:"alternatives-to-using-match-with-resultt-e",level:3},{value:"Shortcuts for Panic on Error: <code>unwrap</code> and <code>expect</code>",id:"shortcuts-for-panic-on-error-unwrap-and-expect",level:3},{value:"Propagating Errors",id:"propagating-errors",level:3},{value:"Where The ? Operator Can Be Used",id:"where-the--operator-can-be-used",level:3},{value:"9.3 - To <code>panic!</code> or Not to <code>panic!</code>",id:"93---to-panic-or-not-to-panic",level:2}],u={toc:p},h="wrapper";function d(e){let{components:t,...n}=e;return(0,a.kt)(h,(0,r.Z)({},u,n,{components:t,mdxType:"MDXLayout"}),(0,a.kt)("h1",{id:"9---error-handling"},"9 - Error Handling"),(0,a.kt)("blockquote",null,(0,a.kt)("p",{parentName:"blockquote"},"Rust has a tiered error-handling scheme:"),(0,a.kt)("ul",{parentName:"blockquote"},(0,a.kt)("li",{parentName:"ul"},"If something might reasonably be absent, Option is used."),(0,a.kt)("li",{parentName:"ul"},"If something goes wrong and can reasonably be handled, Result is used."),(0,a.kt)("li",{parentName:"ul"},"If something goes wrong and cannot reasonably be handled, the thread panics."),(0,a.kt)("li",{parentName:"ul"},"If something catastrophic happens, the program aborts."))),(0,a.kt)("p",null,"-- ",(0,a.kt)("a",{parentName:"p",href:"https://doc.rust-lang.org/nomicon/unwinding.html"},"The Rustonomicon, Chapter 7: Unwinding")),(0,a.kt)("h2",{id:"91---unrecoverable-errors-with-panic"},"9.1 - Unrecoverable Errors with ",(0,a.kt)("inlineCode",{parentName:"h2"},"panic!")),(0,a.kt)("p",null,"We've already discussed a few times when your program will ",(0,a.kt)("em",{parentName:"p"},"panic"),": when you try to index an array or vector out-of-bounds, or when you call ",(0,a.kt)("inlineCode",{parentName:"p"},"expect")," on an ",(0,a.kt)("inlineCode",{parentName:"p"},"Option::None"),", for example."),(0,a.kt)("p",null,"You can also force your program to panic with the ",(0,a.kt)("inlineCode",{parentName:"p"},"panic!")," macro:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'fn main() {\n    panic!("crash and burn");\n}\n')),(0,a.kt)("p",null,"When a panic occurs in the main thread, it halts the program. If the ",(0,a.kt)("inlineCode",{parentName:"p"},"RUST_BACKTRACE=1")," environment variable is set, then the program will also print a stack trace showing where the panic happened, although this only works if the binary contains debug symbols. (If a panic occurs in another thread, it will only halt that thread. See ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch16-fearless-concurrency",title:"Chapter 16: Fearless Concurrency"},"chapter 16"),".)"),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"There's also a ",(0,a.kt)("inlineCode",{parentName:"p"},"todo!")," macro, an ",(0,a.kt)("inlineCode",{parentName:"p"},"unimplemented!")," macro, and an ",(0,a.kt)("inlineCode",{parentName:"p"},"unreachable!")," macro which each work just like the ",(0,a.kt)("inlineCode",{parentName:"p"},"panic!")," macro. These macros differ from ",(0,a.kt)("inlineCode",{parentName:"p"},"panic!")," only in semantics. If you have a function you haven't implemented yet, you might add in ",(0,a.kt)("inlineCode",{parentName:"p"},'todo!("Need to implement this!")')," as a reminder to yourself. If you have a method you need to define to satisfy a trait but you know you will never call it, you could call ",(0,a.kt)("inlineCode",{parentName:"p"},"unimplemented!")," instead of filling in an implementation.")),(0,a.kt)("h3",{id:"unwinding-the-stack-or-aborting-in-response-to-a-panic"},"Unwinding the Stack or Aborting in Response to a Panic"),(0,a.kt)("p",null,"There are two options for what happens when a panic occurs. By default, the program starts ",(0,a.kt)("em",{parentName:"p"},"unwinding"),", which means it starts walking back up the stack, freeing memory and cleaning up data. The alternative is ",(0,a.kt)("em",{parentName:"p"},"aborting")," in which the program just immediately halts and lets the OS clean up everything (if you've ever written a C program, you've probably at some point seen the dreaded message \"segmentation fault (core dumped)\" - aborting is a bit like this)."),(0,a.kt)("p",null,"You can switch to using the abort behavior by adding ",(0,a.kt)("inlineCode",{parentName:"p"},"panic = 'abort'")," to your Cargo.toml file:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-toml"},"[profile.dev]\npanic = 'abort'\n\n[profile.release]\npanic = 'abort'\n")),(0,a.kt)("p",null,"Aborting has the advantage that we don't need all the code for unwinding, so our compiled binary will be smaller. In many cases aborting will be faster than unwinding too. If you want to know more about the differences between aborting an unwinding, ",(0,a.kt)("a",{parentName:"p",href:"https://doc.rust-lang.org/nomicon/unwinding.html"},"see the Rustonomicon"),". Panicking has the advantage that it only terminates a single thread instead of the whole application (although this is the same thing in a single threaded application, and a panic in a thread can cause all sorts of other exciting problems)."),(0,a.kt)("h2",{id:"92---recoverable-errors-with-result"},"9.2 - Recoverable Errors with Result"),(0,a.kt)("p",null,"Many errors can be recovered from. You try to read a file and it doesn't exist, a socket closes unexpectedly, these are not the sorts of things where you typically want to panic. In languages like JavaScript, Java, C++, or Python, these sort os errors are represented as exceptions. In languages like C or Go, errors are explicitly returned from a function."),(0,a.kt)("p",null,"Rust takes this second approach with the ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," enum. Result is similar to the ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch06-enums-and-pattern-matching#the-option-enum-and-its-advantages-over-null-values"},(0,a.kt)("inlineCode",{parentName:"a"},"Option")," enum"),", but instead of being ",(0,a.kt)("inlineCode",{parentName:"p"},"Some")," or ",(0,a.kt)("inlineCode",{parentName:"p"},"None"),", its variants are ",(0,a.kt)("inlineCode",{parentName:"p"},"Ok")," and ",(0,a.kt)("inlineCode",{parentName:"p"},"Err"),":"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},"enum Result<T, E> {\n    Ok(T),\n    Err(E),\n}\n")),(0,a.kt)("p",null,"Much like ",(0,a.kt)("inlineCode",{parentName:"p"},"Option"),", ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," and its two variants are in the prelude, so there's no need to ",(0,a.kt)("inlineCode",{parentName:"p"},"use")," them. Result is generic over both the type of result it returns, and the type of error."),(0,a.kt)("p",null,"Let's see a quick example:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\n\nfn main() {\n    let greeting_file_result = File::open("hello.txt");\n\n    let greeting_file = match greeting_file_result {\n        Ok(file_obj) => file_obj,\n        Err(error) => panic!("Problem opening the file: {:?}", error),\n    };\n}\n')),(0,a.kt)("p",null,"If opening the file is successful, we'll fall into the first arm of the ",(0,a.kt)("inlineCode",{parentName:"p"},"match"),", and ",(0,a.kt)("inlineCode",{parentName:"p"},"file_obj")," will be a ",(0,a.kt)("a",{parentName:"p",href:"https://doc.rust-lang.org/std/fs/struct.File.html"},(0,a.kt)("inlineCode",{parentName:"a"},"File")),". If the file doesn't exist or some other error happens, then ",(0,a.kt)("inlineCode",{parentName:"p"},"error")," will be a ",(0,a.kt)("a",{parentName:"p",href:"https://doc.rust-lang.org/std/io/struct.Error.html"},(0,a.kt)("inlineCode",{parentName:"a"},"std::io::Error")),"."),(0,a.kt)("h3",{id:"matching-on-different-errors"},"Matching on Different Errors"),(0,a.kt)("p",null,"In the previous example, we just panic if an error happens opening the file. But there are different reasons why this might error; the file might not exist, we might not have permission to read it, the network might be down. Let's suppose we want to handle the case where the file doesn't exist by creating the file, and in any other case we'll panic:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\nuse std::io::ErrorKind;\n\nfn main() {\n    let greeting_file_result = File::open("hello.txt");\n\n    let greeting_file = match greeting_file_result {\n        Ok(file) => file,\n        Err(error) => match error.kind() {\n            ErrorKind::NotFound => match File::create("hello.txt") {\n                Ok(fc) => fc,\n                Err(e) => panic!("Problem creating the file: {:?}", e),\n            },\n            other_error => {\n                panic!("Problem opening the file: {:?}", other_error);\n            }\n        },\n    };\n}\n')),(0,a.kt)("p",null,"In the ",(0,a.kt)("inlineCode",{parentName:"p"},"Err")," arm, we're calling ",(0,a.kt)("inlineCode",{parentName:"p"},"error.kind()")," to find out what kind of error this is. This returns a ",(0,a.kt)("inlineCode",{parentName:"p"},"std::io::ErrorKind"),", which is an enum of all the various reasons an ",(0,a.kt)("inlineCode",{parentName:"p"},"io")," operation might fail. We match on the kind, and if it is ",(0,a.kt)("inlineCode",{parentName:"p"},"ErrorKind::NotFound")," we'll try to create the file (which might also fail, so we'll have to deal with that error too!)"),(0,a.kt)("p",null,"If you're a JavaScript programmer who remembers the days before async and await, you might be looking at some of these examples and having flashbacks to the \"pyramid of doom\" - the name JavaScript programmers use for having many deeply nested callbacks. Don't worry just yet - we're going to explore some ways to make that code a little less verbose in the rest of this chapter."),(0,a.kt)("h3",{id:"alternatives-to-using-match-with-resultt-e"},"Alternatives to Using match with ",(0,a.kt)("inlineCode",{parentName:"h3"},"Result<T, E>")),(0,a.kt)("p",null,"That last example had a lot of ",(0,a.kt)("inlineCode",{parentName:"p"},"match")," statements! Fortunately ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," has many methods defined on it which can be used to write more concise versions of the code above. Here's a quick example using the ",(0,a.kt)("inlineCode",{parentName:"p"},"unwrap_or_else")," method:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\nuse std::io::ErrorKind;\n\nfn main() {\n    let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {\n        if error.kind() == ErrorKind::NotFound {\n            File::create("hello.txt").unwrap_or_else(|error| {\n                panic!("Problem creating the file: {:?}", error);\n            })\n        } else {\n            panic!("Problem opening the file: {:?}", error);\n        }\n    });\n}\n')),(0,a.kt)("p",null,"This introduces a new concept called ",(0,a.kt)("em",{parentName:"p"},"closures")," which we'll talk more about in ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch13-functional-language-features",title:"Chapter 13: Functional Language Features: Iterators and Closures"},"chapter 13"),", but if languages you've used have arrow functions or lambdas, you can probably figure out what's going on in this example. (Hint: the ",(0,a.kt)("inlineCode",{parentName:"p"},"|error| { ... }")," creates a function that takes an error as a parameter, similar to an ",(0,a.kt)("inlineCode",{parentName:"p"},"(err) => {...}")," in JavaScript.) If you're having trouble with this example, don't worry - bookmark this and come back to it after you've read ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch13-functional-language-features",title:"Chapter 13: Functional Language Features: Iterators and Closures"},"chapter 13"),"."),(0,a.kt)("h3",{id:"shortcuts-for-panic-on-error-unwrap-and-expect"},"Shortcuts for Panic on Error: ",(0,a.kt)("inlineCode",{parentName:"h3"},"unwrap")," and ",(0,a.kt)("inlineCode",{parentName:"h3"},"expect")),(0,a.kt)("p",null,"When we were learning about ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch06-enums-and-pattern-matching#the-option-enum-and-its-advantages-over-null-values"},"the ",(0,a.kt)("inlineCode",{parentName:"a"},"Option")," enum"),", we learned about the ",(0,a.kt)("inlineCode",{parentName:"p"},"unwrap")," and ",(0,a.kt)("inlineCode",{parentName:"p"},"expect(message)")," methods which panic if the Option is ",(0,a.kt)("inlineCode",{parentName:"p"},"None"),". ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," has ",(0,a.kt)("inlineCode",{parentName:"p"},"unwrap")," and ",(0,a.kt)("inlineCode",{parentName:"p"},"expect")," methods that work similarly, causing a panic if the ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," is an ",(0,a.kt)("inlineCode",{parentName:"p"},"Err")," variant:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\n\nfn main() {\n    let greeting_file = File::open("hello.txt").unwrap();\n\n    let greeting_file2 = File::open("goodbye.txt")\n        .expect("goodbye.txt should have been installed");\n}\n')),(0,a.kt)("p",null,(0,a.kt)("inlineCode",{parentName:"p"},"expect")," is generally preferred over ",(0,a.kt)("inlineCode",{parentName:"p"},"unwrap"),", as it gives more information about what went wrong and gives you a chance to explicitly document the assumptions that were made when you decided to panic here."),(0,a.kt)("h3",{id:"propagating-errors"},"Propagating Errors"),(0,a.kt)("p",null,"Often if an error occurs in a function, we don't want to handle the error ourselves but propagate the error to the function's caller. If you're coming to Rust from Go, you've no doubt written ",(0,a.kt)("inlineCode",{parentName:"p"},"if err != nil { return err }")," many times in your career. In most other languages, when we throw an exception, we're used to it traveling up the stack to the closest ",(0,a.kt)("inlineCode",{parentName:"p"},"catch"),"."),(0,a.kt)("p",null,"Here's a very verbose example of a function that reads a username from a file. If the file can't be read, we don't want ",(0,a.kt)("inlineCode",{parentName:"p"},"read_username_from_file")," to panic, but we also don't know how to handle the error here. We want to return the error back to the caller so the caller can decide what to do about the fact that we can't find the username:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\nuse std::io::{self, Read};\n\n// This function is so long!  We can make it shorter!\nfn read_username_from_file() -> Result<String, io::Error> {\n    let username_file_result = File::open("hello.txt");\n\n    let mut username_file = match username_file_result {\n        Ok(file) => file,\n        Err(e) => return Err(e),\n    };\n\n    let mut username = String::new();\n\n    match username_file.read_to_string(&mut username) {\n        Ok(_) => Ok(username),\n        Err(e) => Err(e),\n    }\n}\n')),(0,a.kt)("p",null,"One important thing to note here is that ",(0,a.kt)("inlineCode",{parentName:"p"},"read_username_from_file")," returns a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result<String, io:Error>"),". We chose ",(0,a.kt)("inlineCode",{parentName:"p"},"io:Error")," for the ",(0,a.kt)("inlineCode",{parentName:"p"},"E")," part of ",(0,a.kt)("inlineCode",{parentName:"p"},"Result<T, E>"),", because this is the error type that both of the functions we call can return. We can use a shortcut called the ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," operator to reduce a lot of this boilerplate:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\nuse std::io::{self, Read};\n\nfn read_username_from_file() -> Result<String, io::Error> {\n    let mut username_file = File::open("hello.txt")?;\n    let mut username = String::new();\n    username_file.read_to_string(&mut username)?;\n    Ok(username)\n}\n')),(0,a.kt)("p",null,"The ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," operator can be placed after any ",(0,a.kt)("inlineCode",{parentName:"p"},"Result"),", and basically is the same as the ",(0,a.kt)("inlineCode",{parentName:"p"},"match")," expression from the original example. The ",(0,a.kt)("inlineCode",{parentName:"p"},"?"),' says: "If ',(0,a.kt)("inlineCode",{parentName:"p"},"result")," is an ",(0,a.kt)("inlineCode",{parentName:"p"},"Ok")," variant, resolve this expression to the value of the ",(0,a.kt)("inlineCode",{parentName:"p"},"Ok"),". If ",(0,a.kt)("inlineCode",{parentName:"p"},"result")," is an ",(0,a.kt)("inlineCode",{parentName:"p"},"Err")," then ",(0,a.kt)("inlineCode",{parentName:"p"},"return result"),'". This makes errors abort early and return to the caller, very similar to how exceptions work.'),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"Here we're adding a ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," to a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result<*, io:Error>")," and we're returning a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result<*, io:Error>")," - since the error types are the same, we can use ",(0,a.kt)("inlineCode",{parentName:"p"},"?"),", but note that the error types don't have to be the same! The ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," operator will pass errors through the ",(0,a.kt)("inlineCode",{parentName:"p"},"from")," function from the ",(0,a.kt)("inlineCode",{parentName:"p"},"From")," trait on our return type to convert the error from one error type to another."),(0,a.kt)("p",{parentName:"admonition"},"For example, if we wanted to defined a custom error type named ",(0,a.kt)("inlineCode",{parentName:"p"},"OurError"),", we could define ",(0,a.kt)("inlineCode",{parentName:"p"},"impl From<io::Error> for OurError")," to tell Rust how to convert ",(0,a.kt)("inlineCode",{parentName:"p"},"io:Error"),"s to ",(0,a.kt)("inlineCode",{parentName:"p"},"OurError"),"s, without needing to add any more code to our example."),(0,a.kt)("p",{parentName:"admonition"},"See ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch10/ch10-02-traits#from-and-into"},"chapter 10")," for more information about the ",(0,a.kt)("inlineCode",{parentName:"p"},"From")," and ",(0,a.kt)("inlineCode",{parentName:"p"},"Into")," traits.")),(0,a.kt)("p",null,"We can shorten this method further by eliminating some variable names and using chaining:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\nuse std::io::{self, Read};\n\nfn read_username_from_file() -> Result<String, io::Error> {\n    let mut username = String::new();\n    File::open("hello.txt")?.read_to_string(&mut username)?;\n    Ok(username)\n}\n')),(0,a.kt)("p",null,"But of course reading a file to a string is a fairly common operation, and the standard library provides a function to do it, so we can shorten this even further:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs;\nuse std::io;\n\nfn read_username_from_file() -> Result<String, io::Error> {\n    fs::read_to_string("hello.txt")\n}\n')),(0,a.kt)("h3",{id:"where-the--operator-can-be-used"},"Where The ? Operator Can Be Used"),(0,a.kt)("p",null,(0,a.kt)("inlineCode",{parentName:"p"},"?")," can be used with both ",(0,a.kt)("inlineCode",{parentName:"p"},"Result"),"s and ",(0,a.kt)("inlineCode",{parentName:"p"},"Option"),"s. In the ",(0,a.kt)("inlineCode",{parentName:"p"},"Option")," case it works a little bit like ",(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining"},"JavaScript's optional chaining operator"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},"fn last_char_of_first_line(text: &str) -> Option<char> {\n    text.lines().next()?.chars().last()\n}\n")),(0,a.kt)("p",null,"Here ",(0,a.kt)("inlineCode",{parentName:"p"},"text")," might be the empty string, or perhaps it's a string like ",(0,a.kt)("inlineCode",{parentName:"p"},'"\\nfoo"')," where the first line has no last char, so this has to return an ",(0,a.kt)("inlineCode",{parentName:"p"},"Option"),". Note that here too, just like a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result"),", the ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," will turn into a ",(0,a.kt)("inlineCode",{parentName:"p"},"return")," statement if the ",(0,a.kt)("inlineCode",{parentName:"p"},"Option")," is an ",(0,a.kt)("inlineCode",{parentName:"p"},"Option::None")," and return from the whole function. This is quite different from the JavaScript version, where it just ignores the rest of the expression."),(0,a.kt)("p",null,"Since using the ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," operator can turn into a early ",(0,a.kt)("inlineCode",{parentName:"p"},"return")," statement, the return type of your function must match what ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," is going to return. If you use ",(0,a.kt)("inlineCode",{parentName:"p"},"?")," on a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," then your function has to return a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," with a compatible error type, and if you use it on an ",(0,a.kt)("inlineCode",{parentName:"p"},"Option")," your function must return an ",(0,a.kt)("inlineCode",{parentName:"p"},"Option"),". This, for example, is not going to compile:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::fs::File;\n\nfn main() {\n    // Can\'t use `?` here!\n    let greeting_file = File::open("hello.txt")?;\n}\n')),(0,a.kt)("p",null,"This happens because the function signature for ",(0,a.kt)("inlineCode",{parentName:"p"},"main")," implicitly declares that it returns ",(0,a.kt)("inlineCode",{parentName:"p"},"()"),", not a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result"),". Up until now all our ",(0,a.kt)("inlineCode",{parentName:"p"},"main")," functions have had this signature, but Rust allows us to return a ",(0,a.kt)("inlineCode",{parentName:"p"},"Result")," from ",(0,a.kt)("inlineCode",{parentName:"p"},"main"),":"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-rust"},'use std::error::Error;\nuse std::fs::File;\n\nfn main() -> Result<(), Box<dyn Error>> {\n    let greeting_file = File::open("hello.txt")?;\n\n    Ok(())\n}\n')),(0,a.kt)("p",null,"Whoa! What's this ",(0,a.kt)("inlineCode",{parentName:"p"},"Box<dyn Error>"),"? This is a ",(0,a.kt)("em",{parentName:"p"},"trait object"),", which we'll discuss in ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch17-object-oriented-features#172---using-trait-objects-that-allow-for-values-of-different-types"},"chapter 17"),'. For now, know that this means "any kind of error". When ',(0,a.kt)("inlineCode",{parentName:"p"},"main")," returns, if it returns an ",(0,a.kt)("inlineCode",{parentName:"p"},"Ok")," variant, the program will terminate and return 0 ",(0,a.kt)("a",{parentName:"p",href:"https://en.wikipedia.org/wiki/Exit_status"},"exit code")," to the shell, signalling the program terminated correctly. If it returns an ",(0,a.kt)("inlineCode",{parentName:"p"},"Err")," variant, the error will be printed to stderr and the program will return a 1 to the shell to signal an error."),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"The ",(0,a.kt)("inlineCode",{parentName:"p"},"main")," function can return other types too! It can return anything that implements the ",(0,a.kt)("a",{parentName:"p",href:"https://doc.rust-lang.org/stable/std/process/trait.Termination.html"},(0,a.kt)("inlineCode",{parentName:"a"},"std::process::Termination")," trait"),".")),(0,a.kt)("h2",{id:"93---to-panic-or-not-to-panic"},"9.3 - To ",(0,a.kt)("inlineCode",{parentName:"h2"},"panic!")," or Not to ",(0,a.kt)("inlineCode",{parentName:"h2"},"panic!")),(0,a.kt)("p",null,"If you're an experienced programmer, your language of choice probably has a way to handle errors and something much like panic. You know this stuff, you can probably safely ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch10/ch10-01-generic-data-types",title:"Chapter 10: Generic Types, Traits, and Lifetimes"},"skip ahead to the next chapter"),"."),(0,a.kt)("p",null,"If you're still here: A panic halts the entire program, so should be used sparingly. There are some times where it's good to use ",(0,a.kt)("inlineCode",{parentName:"p"},"expect"),", ",(0,a.kt)("inlineCode",{parentName:"p"},"unwrap"),", and ",(0,a.kt)("inlineCode",{parentName:"p"},"panic!"),":"),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},"In ",(0,a.kt)("a",{parentName:"li",href:"/rust-book-abridged/ch11-automated-tests",title:"Chapter 11: Writing Automated Tests"},"unit tests"),", where you know there isn't supposed to be an error, and you want to fail the test immediately if there is."),(0,a.kt)("li",{parentName:"ul"},"When you know something should never happen. It's perfectly OK to write ",(0,a.kt)("inlineCode",{parentName:"li"},'let home: IpAddr = "127.0.0.1".parse().unwrap();')," because you know this string will parse to a valid IP address."),(0,a.kt)("li",{parentName:"ul"},"When you have detected your program is in an ",(0,a.kt)("em",{parentName:"li"},"invalid state"),". If you're trying to work out the percentage likelihood that something will happen and you arrive at 200%, then you know there's a bug in your function, and a panic might be reasonable. Even better than panicking when you find you have invalid state, though, is to make it so invalid state cannot be represented in your program. We'll talk a bit about this in ",(0,a.kt)("a",{parentName:"li",href:"/rust-book-abridged/ch17-object-oriented-features",title:"Chapter 17: Object Oriented Features of Rust"},"chapter 17"),"."),(0,a.kt)("li",{parentName:"ul"},"If your function has a ",(0,a.kt)("em",{parentName:"li"},"contract")," and the values passed in violate that contract, it might make sense to panic. If your function's documentation clearly states that it requires a value between 0 and 1, and someone passes in a 7, then if you believe this clearly represents an error somewhere in the caller's code, a panic is appropriate. If an illegal value could create some kind of security risk or correctness risk, then a panic is definitely warranted. If your function is already returning a ",(0,a.kt)("inlineCode",{parentName:"li"},"Result")," anyways, it might make sense to just add an error though."),(0,a.kt)("li",{parentName:"ul"},"If you're writing a book about Rust and you want your examples to be short and concise, and a lot of error handling code would obscure the points you are trying to make, then a panic is fine.")),(0,a.kt)("p",null,"There are some places where it's a terrible idea to panic. When you panic inside a function, callers of that function have no easy way to recover from the panic. These are places where it's better to return an error:"),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},"When you encounter an error that is unlikely, but could happen in normal operation of the program."),(0,a.kt)("li",{parentName:"ul"},"When you're authoring a library. Callers to your library might like the opportunity to abort an operation or try again, instead of crashing the entire application.")),(0,a.kt)("admonition",{type:"info"},(0,a.kt)("p",{parentName:"admonition"},"We said that a program can't recover from a panic. This is not ",(0,a.kt)("em",{parentName:"p"},"strictly")," true, as there is a ",(0,a.kt)("a",{parentName:"p",href:"https://doc.rust-lang.org/std/panic/fn.catch_unwind.html"},(0,a.kt)("inlineCode",{parentName:"a"},"catch_unwind")," function")," in Rust. But this is not something intended to be used for day-to-day error handling.")),(0,a.kt)("p",null,"Continue to ",(0,a.kt)("a",{parentName:"p",href:"/rust-book-abridged/ch10/ch10-01-generic-data-types",title:"Chapter 10: Generic Types, Traits, and Lifetimes"},"chapter 10"),"."))}d.isMDXComponent=!0}}]);